export const companyModel = {
  id: null,
  name: "",
  email: "",
  mobileNumber: "",
  phoneNumber: "",
  details: "",
  technologies: [],
  companyBenefits: [],
  ceo: "",
  foundedIn: "",
  employees: 0,
  markets: [],
  countries: [],
  logoUrl: "default-user.png",
  isActive: true,
};
