export const jobModel = {
  title: "",
  slug: "",
  category: [],
  subCategory: [],
  tag: [],
  details: "",
  qualifications: "",
  responsibilities: "",
  keyword: [],
  metaDescription: "",
  metaTitle: "",
  author: "",
  featuredImageUrl: "",
  featuredImageTitle: "",
  featuredImageCaptions: "",
  featuredImageDescriptions: "",
  featuredImageAltText: "",
  isActive: true,
};
