/** @format */

export const GET_ALL_PROPERTIES_BY_QUERY = 'GET_ALL_PROPERTIES_BY_QUERY';
export const BIND_PROPERTY_INFO = 'BIND_PROPERTY_INFO';
export const GET_USER_PROPERTIES = 'GET_USER_PROPERTIES';
export const GET_ALL_PROPERTIES = 'GET_ALL_PROPERTIES';
