export const GET_USERS = 'GET_USERS';
export const GET_USERS_BY_QUERY = 'GET_USERS_BY_QUERY';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const USER_DATA_ON_PROGRESS = 'USER_DATA_ON_PROGRESS';
export const USER_DATA_SUBMIT_PROGRESS = 'USER_DATA_SUBMIT_PROGRESS';
export const OPEN_USER_SIDEBAR = 'OPEN_USER_SIDEBAR';
export const BIND_USER_BASIC_INFO = 'BIND_USER_BASIC_INFO';
export const BIND_USER_ATTRIBUTES = 'BIND_USER_ATTRIBUTES';
