export const blogModel = {
  title: "",
  slug: "",
  category: [],
  subCategory: [],
  tag: [],
  details: "",
  qualifications: "",
  responsibilities: "",
  keyword: [],
  metaDescription: "",
  metaTitle: "",
  author: "",
  featuredImageUrl: "",
  videoLink: "",
  applyLink: "",
  pdfLink: "",
  isActive: true,
};
